version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: english_trainer_db
    restart: always
    env_file:
      - .env  # Переменные окружения вынесены в отдельный файл
    ports:
      - "5432:5432"  # Проброс порта для подключения
    volumes:
      - db_data:/var/lib/postgresql/data  # Данные БД сохраняются между перезапусками
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Скрипт инициализации

volumes:
  db_data: 